spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_pets
    username: mypets
    password: nUWhgcPUz8uxBp2n9LKu
  jpa:
    hibernate:
      ddl-auto:update
    generate-ddl: true

auth:
  jwt:
    issuer: "My Pets"
    audience: "My Pets API"
    ttl-in-seconds: 3600
    secret: "771x/pgLxX5teANIWtGvC1XzPJTFnp3QAHRR5n/qAVgmSdvySB6TiX2j11A5IVkpaSz2z+V1pn7FVHPcmen/qn5TWklueGJO6h43gjzPLsurnF1N6ptcDZRDRPz0eEpF8FXq+xY+X1Gp6CeO3irTVdNa5pNMUndzH4CdjLQf/66kB3kYq2os0IaRBwMX6EKsDIlHi2/af+6h4zeXLEvffchmgmHRn6Ilhkw7Yw=="